In [7]:
import pandas as pd 

BASE = ('dados_transacoes.csv')  

df = pd.read_csv(BASE)

df.head()

,id_cliente,data_transação,categoria_produto,idade,genero,preco,quantidade
0,fb3e7183-2f2b-49f0-b6fc-7bb82f62ab66,01/01/2024,Eletrônicos,56,Masculino,3077.35,1
1,554138dc-b472-4420-9e50-46fe24262598,11/01/2024,Eletrônicos,69,Masculino,3937.89,1
2,69361fcc-d6ea-44ed-9511-4d08cb5d5ec5,29/02/2024,Alimentos,46,Feminino,8.15,3
3,119a726d-e9f5-4ebc-bd72-c10e332182a0,10/04/2024,Roupas,32,Feminino,150.71,3
4,b48da9ae-f9a5-4866-a977-30571fc8496d,15/02/2024,Roupas,60,Feminino,103.89,4

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_cliente         50000 non-null  object
 1   data_transação     50000 non-null  object
 2   categoria_produto  50000 non-null  object
 3   idade              50000 non-null  int64
 4   genero             50000 non-null  object
 5   preco              50000 non-null  float64
 6   quantidade         50000 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 2.7+ MB

In [9]:
df.describe()

              idade         preco    quantidade
count  50000.000000  50000.000000  50000.000000
mean      44.002820    774.603907      2.293920
std       15.269871   1193.081061      1.934571
min       18.000000      5.000000      1.000000
25%       31.000000     46.297500      1.000000
50%       44.000000    179.895000      2.000000
75%       57.000000   1016.612500      3.000000
max       70.000000   4999.510000      9.000000

In [10]:
df.describe(exclude='number')

,id_cliente,data_transação,categoria_produto,genero
count,50000,50000,50000,50000
unique,50000,134,5,2
top,fb3e7183-2f2b-49f0-b6fc-7bb82f62ab66,13/01/2024,Livros,Masculino
freq,1,445,10259,25072

In [12]:
df.groupby('categoria_produto')['preco'].mean()

categoria_produto
Alimentos           27.652067
Casa & Cozinha     845.711708
Eletrônicos       2749.545066
Livros             102.403509
Roupas             154.996166
Name: preco, dtype: float64

In [13]:
df.groupby(['categoria_produto','genero'])['preco'].mean()

categoria_produto  genero
Alimentos          Feminino       27.503085
                   Masculino      27.804396
Casa & Cozinha     Feminino      849.303521
                   Masculino     842.147386
Eletrônicos        Feminino     2748.968288
                   Masculino    2750.131264
Livros             Feminino      101.765570
                   Masculino     103.010978
Roupas             Feminino      155.129628
                   Masculino     154.863932
Name: preco, dtype: float64

In [15]:
%timeit df.groupby('categoria_produto')['preco'].mean()
%timeit df.groupby(['categoria_produto','genero'])['preco'].mean()

3.71 ms ± 911 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
12 ms ± 393 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [16]:
df_otimizado = df.copy()

df_otimizado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_cliente         50000 non-null  object
 1   data_transação     50000 non-null  object
 2   categoria_produto  50000 non-null  object
 3   idade              50000 non-null  int64
 4   genero             50000 non-null  object
 5   preco              50000 non-null  float64
 6   quantidade         50000 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 2.7+ MB

In [17]:
df_otimizado['data_transação'] = pd.to_datetime(df_otimizado['data_transação'],format='%d/%m/%Y')

df_otimizado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_cliente         50000 non-null  object
 1   data_transação     50000 non-null  datetime64[ns]
 2   categoria_produto  50000 non-null  object
 3   idade              50000 non-null  int64
 4   genero             50000 non-null  object
 5   preco              50000 non-null  float64
 6   quantidade         50000 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 2.7+ MB

In [18]:
df_otimizado.head()

,id_cliente,data_transação,categoria_produto,idade,genero,preco,quantidade
0,fb3e7183-2f2b-49f0-b6fc-7bb82f62ab66,2024-01-01,Eletrônicos,56,Masculino,3077.35,1
1,554138dc-b472-4420-9e50-46fe24262598,2024-01-11,Eletrônicos,69,Masculino,3937.89,1
2,69361fcc-d6ea-44ed-9511-4d08cb5d5ec5,2024-02-29,Alimentos,46,Feminino,8.15,3
3,119a726d-e9f5-4ebc-bd72-c10e332182a0,2024-04-10,Roupas,32,Feminino,150.71,3
4,b48da9ae-f9a5-4866-a977-30571fc8496d,2024-02-15,Roupas,60,Feminino,103.89,4

In [20]:
df_otimizado['data_transação'].dt.month

0        1
1        1
2        2
3        4
4        2
        ..
49995    1
49996    4
49997    3
49998    2
49999    1
Name: data_transação, Length: 50000, dtype: int32

In [21]:
df_otimizado['categoria_produto'] = df_otimizado['categoria_produto'].astype('category')
df_otimizado['genero'] = df_otimizado['genero'].astype('category')

df_otimizado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_cliente         50000 non-null  object
 1   data_transação     50000 non-null  datetime64[ns]
 2   categoria_produto  50000 non-null  category
 3   idade              50000 non-null  int64
 4   genero             50000 non-null  category
 5   preco              50000 non-null  float64
 6   quantidade         50000 non-null  int64
dtypes: category(2), datetime64[ns](1), float64(1), int64(2), object(1)
memory usage: 2.0+ MB

In [22]:
import sys

sys.maxsize

9223372036854775807

In [23]:
sys.float_info.max

1.7976931348623157e+308

In [24]:
colunas_float = df_otimizado.select_dtypes(include='float64').columns
colunas_int = df_otimizado.select_dtypes(include='int64').columns

colunas_float, colunas_int

(Index(['preco'], dtype='object'),
 Index(['idade', 'quantidade'], dtype='object'))

In [26]:
df_otimizado[colunas_float] = df_otimizado[colunas_float].apply(pd.to_numeric, downcast='float')
df_otimizado[colunas_int] = df_otimizado[colunas_int].apply(pd.to_numeric, downcast='integer')

In [27]:
df_otimizado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_cliente         50000 non-null  object
 1   data_transação     50000 non-null  datetime64[ns]
 2   categoria_produto  50000 non-null  category
 3   idade              50000 non-null  int8
 4   genero             50000 non-null  category
 5   preco              50000 non-null  float32
 6   quantidade         50000 non-null  int8
dtypes: category(2), datetime64[ns](1), float32(1), int8(2), object(1)
memory usage: 1.1+ MB

In [29]:
df_otimizado.memory_usage().sum() / df.memory_usage().sum()

np.float64(0.4287183604201516)

In [31]:
df.describe()

              idade         preco    quantidade
count  50000.000000  50000.000000  50000.000000
mean      44.002820    774.603907      2.293920
std       15.269871   1193.081061      1.934571
min       18.000000      5.000000      1.000000
25%       31.000000     46.297500      1.000000
50%       44.000000    179.895000      2.000000
75%       57.000000   1016.612500      3.000000
max       70.000000   4999.510000      9.000000

In [30]:
df_otimizado.describe()

                   data_transação         idade         preco    quantidade
count                       50000  50000.000000  50000.000000  50000.000000
mean   2024-03-07 11:25:19.488000     44.002820    774.603821      2.293920
min           2024-01-01 00:00:00     18.000000      5.000000      1.000000
25%           2024-02-03 00:00:00     31.000000     46.297500      1.000000
50%           2024-03-07 00:00:00     44.000000    179.894997      2.000000
75%           2024-04-11 00:00:00     57.000000   1016.612518      3.000000
max           2024-05-13 00:00:00     70.000000   4999.509766      9.000000
std                           NaN     15.269871   1193.081055      1.934571

In [33]:
%timeit df.groupby('categoria_produto')['preco'].mean()
%timeit df.groupby(['categoria_produto','genero'])['preco'].mean()

3.2 ms ± 114 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
6.09 ms ± 447 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [32]:
%timeit df_otimizado.groupby('categoria_produto')['preco'].mean()
%timeit df_otimizado.groupby(['categoria_produto','genero'])['preco'].mean()

<magic-timeit>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

The slowest run took 4.18 times longer than the fastest. This could mean that an intermediate result is being cached.
783 μs ± 563 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
11.3 ms ± 312 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)