In [1]:
import pandas as pd

dados_pedidos = {
    "ID_Pedido": [501, 502, 503, 504, 505, 506, 507],
    "Cliente": ["Lucas", "Mariana", "Lucas", "Beatriz", "Roberto", "Mariana", "Lucas"],
    "Prato": ["Hambúrguer", "Pizza", "Sushi", "Salada", "Hambúrguer", "Sushi", "Pizza"],
    "Preco_R$": [35, 60, 85, 28, 42, 90, 55],
    "Entregue": [True, True, False, True, True, False, True]
}

df_pedidos = pd.DataFrame(dados_pedidos)
df_pedidos

   ID_Pedido  Cliente       Prato  Preco_R$  Entregue
0        501    Lucas  Hambúrguer        35      True
1        502  Mariana       Pizza        60      True
2        503    Lucas       Sushi        85     False
3        504  Beatriz      Salada        28      True
4        505  Roberto  Hambúrguer        42      True
5        506  Mariana       Sushi        90     False
6        507    Lucas       Pizza        55      True

In [ ]:
# Missão 5 (Mutação/Coluna Nova): Crie uma coluna chamada "Pedido_Caro" que receba True para pedidos com Preco_R$ maior que 50, e False para o restante.

In [5]:
df_resumo_pedidos = ["Cliente","Prato","Preco_R$"]
df_pedidos[df_resumo_pedidos]

   Cliente       Prato  Preco_R$
0    Lucas  Hambúrguer        35
1  Mariana       Pizza        60
2    Lucas       Sushi        85
3  Beatriz      Salada        28
4  Roberto  Hambúrguer        42
5  Mariana       Sushi        90
6    Lucas       Pizza        55

In [8]:
df_hamburguer = df_pedidos[df_pedidos["Prato"] == "Hambúrguer"]
df_hamburguer

   ID_Pedido  Cliente       Prato  Preco_R$  Entregue
0        501    Lucas  Hambúrguer        35      True
4        505  Roberto  Hambúrguer        42      True

In [10]:
df_lucas = df_pedidos[(df_pedidos["Cliente"] == "Lucas") & (df_pedidos["Preco_R$"] > 40)]
df_lucas

   ID_Pedido Cliente  Prato  Preco_R$  Entregue
2        503   Lucas  Sushi        85     False
6        507   Lucas  Pizza        55      True

In [11]:
df_pedidos.groupby("Cliente")["Preco_R$"].sum().reset_index()

   Cliente  Preco_R$
0  Beatriz        28
1    Lucas       175
2  Mariana       150
3  Roberto        42

In [12]:
df_pedidos["Pedido_caro"]= df_pedidos["Preco_R$"] > 50
df_pedidos

   ID_Pedido  Cliente       Prato  Preco_R$  Entregue  Pedido_caro
0        501    Lucas  Hambúrguer        35      True        False
1        502  Mariana       Pizza        60      True         True
2        503    Lucas       Sushi        85     False         True
3        504  Beatriz      Salada        28      True        False
4        505  Roberto  Hambúrguer        42      True        False
5        506  Mariana       Sushi        90     False         True
6        507    Lucas       Pizza        55      True         True