In [2]:
import pandas as pd

dados_exames = {
    "ID_Atendimento": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
    "Paciente": ["Ana", "Bruno", "Carla", "Daniel", "Eduarda", "Fábio", "Gabriela", "Hugo"],
    "Setor": ["Bioquimica", "Hematologia", "Bioquimica", "Imunologia", "Hematologia", "Bioquimica", "Imunologia", "Hematologia"],
    "Tempo_Espera_Min": [25, 50, 12, 45, 60, 30, 18, 55],
    "Urgente": [False, True, False, False, True, False, False, True]
}

df_exames = pd.DataFrame(dados_exames)
df_exames

   ID_Atendimento  Paciente        Setor  Tempo_Espera_Min  Urgente
0            1001       Ana   Bioquimica                25    False
1            1002     Bruno  Hematologia                50     True
2            1003     Carla   Bioquimica                12    False
3            1004    Daniel   Imunologia                45    False
4            1005   Eduarda  Hematologia                60     True
5            1006     Fábio   Bioquimica                30    False
6            1007  Gabriela   Imunologia                18    False
7            1008      Hugo  Hematologia                55     True

In [3]:
df_resumo_pacientes = ["Paciente","Setor","Tempo_Espera_Min"]
df_exames[df_resumo_pacientes]

   Paciente        Setor  Tempo_Espera_Min
0       Ana   Bioquimica                25
1     Bruno  Hematologia                50
2     Carla   Bioquimica                12
3    Daniel   Imunologia                45
4   Eduarda  Hematologia                60
5     Fábio   Bioquimica                30
6  Gabriela   Imunologia                18
7      Hugo  Hematologia                55

In [ ]:
# Missão 5 (Ordenação): Pegue o resultado da Missão 4 e ordene do setor com mais exames para o setor com menos exames usando .sort_values(ascending=False).

In [4]:
df_hemato = df_exames[(df_exames["Setor"] == "Hematologia") & (df_exames["Tempo_Espera_Min"] > 40)]
df_hemato

   ID_Atendimento Paciente        Setor  Tempo_Espera_Min  Urgente
1            1002    Bruno  Hematologia                50     True
4            1005  Eduarda  Hematologia                60     True
7            1008     Hugo  Hematologia                55     True

In [11]:
df_exames["Atendimento_Lento"] = df_exames["Tempo_Espera_Min"] > 35
df_atraso = ["Paciente","Atendimento_Lento"]
df_exames[df_atraso]

   Paciente  Atendimento_Lento
0       Ana              False
1     Bruno               True
2     Carla              False
3    Daniel               True
4   Eduarda               True
5     Fábio              False
6  Gabriela              False
7      Hugo               True

In [4]:
df_exames

   ID_Atendimento  Paciente        Setor  Tempo_Espera_Min  Urgente
0            1001       Ana   Bioquimica                25    False
1            1002     Bruno  Hematologia                50     True
2            1003     Carla   Bioquimica                12    False
3            1004    Daniel   Imunologia                45    False
4            1005   Eduarda  Hematologia                60     True
5            1006     Fábio   Bioquimica                30    False
6            1007  Gabriela   Imunologia                18    False
7            1008      Hugo  Hematologia                55     True

In [6]:
df_exames.groupby("Setor")["ID_Atendimento"].count().reset_index()

         Setor  ID_Atendimento
0   Bioquimica               3
1  Hematologia               3
2   Imunologia               2

In [8]:
df_exames.groupby("Setor")["ID_Atendimento"].count().sort_values(ascending=True).reset_index()

         Setor  ID_Atendimento
0   Imunologia               2
1   Bioquimica               3
2  Hematologia               3