In [1]:
import pandas as pd

dados_vendas = {
    "ID_Venda": [201, 202, 203, 204, 205, 206, 207],
    "Vendedor": ["Carlos", "Fernanda", "Carlos", "Beatriz", "Fernanda", "Beatriz", "Carlos"],
    "Categoria": ["Eletrônicos", "Moda", "Eletrônicos", "Higiene", "Moda", "Eletrônicos", "Higiene"],
    "Valor_R$": [1500, 200, 800, 50, 350, 2100, 90],
    "Comissao_Paga": [True, True, False, True, False, True, False]
}

df_vendas = pd.DataFrame(dados_vendas)
df_vendas

   ID_Venda  Vendedor    Categoria  Valor_R$  Comissao_Paga
0       201    Carlos  Eletrônicos      1500           True
1       202  Fernanda         Moda       200           True
2       203    Carlos  Eletrônicos       800          False
3       204   Beatriz      Higiene        50           True
4       205  Fernanda         Moda       350          False
5       206   Beatriz  Eletrônicos      2100           True
6       207    Carlos      Higiene        90          False

In [4]:
df_resumo_vendas = ["Vendedor", "Categoria","Valor_R$"]
df_vendas[df_resumo_vendas]

   Vendedor    Categoria  Valor_R$
0    Carlos  Eletrônicos      1500
1  Fernanda         Moda       200
2    Carlos  Eletrônicos       800
3   Beatriz      Higiene        50
4  Fernanda         Moda       350
5   Beatriz  Eletrônicos      2100
6    Carlos      Higiene        90

In [5]:
df_carlos = df_vendas[df_vendas["Vendedor"] == "Carlos"]
df_carlos

   ID_Venda Vendedor    Categoria  Valor_R$  Comissao_Paga
0       201   Carlos  Eletrônicos      1500           True
2       203   Carlos  Eletrônicos       800          False
6       207   Carlos      Higiene        90          False

In [9]:
df_vendas_eletronicos = df_vendas[(df_vendas["Categoria"] == "Eletrônicos") & (df_vendas["Valor_R$"] > 1000)]
df_vendas_eletronicos

   ID_Venda Vendedor    Categoria  Valor_R$  Comissao_Paga
0       201   Carlos  Eletrônicos      1500           True
5       206  Beatriz  Eletrônicos      2100           True

In [10]:
df_vendas.groupby("Vendedor")["Valor_R$"].sum().reset_index()

   Vendedor  Valor_R$
0   Beatriz      2150
1    Carlos      2390
2  Fernanda       550

In [12]:
df_vendas["Venda_Alta"] = df_vendas["Valor_R$"] > 500
df_vendas

   ID_Venda  Vendedor    Categoria  Valor_R$  Comissao_Paga  Venda_Alta
0       201    Carlos  Eletrônicos      1500           True        True
1       202  Fernanda         Moda       200           True       False
2       203    Carlos  Eletrônicos       800          False        True
3       204   Beatriz      Higiene        50           True       False
4       205  Fernanda         Moda       350          False       False
5       206   Beatriz  Eletrônicos      2100           True        True
6       207    Carlos      Higiene        90          False       False