In [ ]:
# Nova Coluna / Condicional: Crie uma coluna nova chamada 'Urgente'.

# Se o tempo for maior que 40 minutos, o valor deve ser True.

# Se for menor ou igual a 40, o valor deve ser False.
# (Dica: dá pra fazer direto com df['Tempo_Minutos'] > 40)

In [24]:
import pandas as pd

dados = {
    'ID_Exame': [101, 102, 103, 104, 105, 106, 107],
    'Paciente': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eduardo', 'Fernanda', 'Gabriel'],
    'Setor': ['Hematologia', 'Bioquimica', 'Hematologia', 'Imunologia', 'Bioquimica', 'Hematologia', 'Imunologia'],
    'Tempo_Minutos': [12, 45, 18, 60, 30, 15, 90],
    'Status': ['Concluido', 'Pendente', 'Concluido', 'Pendente', 'Concluido', 'Concluido', 'Cancelado']
}

df_relatorio = pd.DataFrame(dados)
df_relatorio

   ID_Exame  Paciente        Setor  Tempo_Minutos     Status
0       101       Ana  Hematologia             12  Concluido
1       102     Bruno   Bioquimica             45   Pendente
2       103    Carlos  Hematologia             18  Concluido
3       104   Daniela   Imunologia             60   Pendente
4       105   Eduardo   Bioquimica             30  Concluido
5       106  Fernanda  Hematologia             15  Concluido
6       107   Gabriel   Imunologia             90  Cancelado

In [ ]:
df_visao_geral = ["Paciente","Setor","Status"]
df_relatorio[df_visao_geral]

   Paciente        Setor     Status
0       Ana  Hematologia  Concluido
1     Bruno   Bioquimica   Pendente
2    Carlos  Hematologia  Concluido
3   Daniela   Imunologia   Pendente
4   Eduardo   Bioquimica  Concluido
5  Fernanda  Hematologia  Concluido
6   Gabriel   Imunologia  Cancelado

In [ ]:
df_hemato = df_relatorio[df_relatorio["Setor"]=="Hematologia"]
df_hemato

   ID_Exame  Paciente        Setor  Tempo_Minutos     Status
0       101       Ana  Hematologia             12  Concluido
2       103    Carlos  Hematologia             18  Concluido
5       106  Fernanda  Hematologia             15  Concluido

In [ ]:
df_problemas = df_relatorio[(df_relatorio["Status"]== "Pendente") & (df_relatorio["Tempo_Minutos"] >30)]
df_problemas

   ID_Exame Paciente       Setor  Tempo_Minutos    Status
1       102    Bruno  Bioquimica             45  Pendente
3       104  Daniela  Imunologia             60  Pendente

In [32]:
df_relatorio.groupby("Setor")["Tempo_Minutos"].mean().reset_index()

         Setor  Tempo_Minutos
0   Bioquimica           37.5
1  Hematologia           15.0
2   Imunologia           75.0

In [38]:
df_relatorio["Urgente"] = df_relatorio["Tempo_Minutos"] > 40
df_relatorio

   ID_Exame  Paciente        Setor  Tempo_Minutos     Status  Urgente
0       101       Ana  Hematologia             12  Concluido    False
1       102     Bruno   Bioquimica             45   Pendente     True
2       103    Carlos  Hematologia             18  Concluido    False
3       104   Daniela   Imunologia             60   Pendente     True
4       105   Eduardo   Bioquimica             30  Concluido    False
5       106  Fernanda  Hematologia             15  Concluido    False
6       107   Gabriel   Imunologia             90  Cancelado     True