In [3]:
import pandas as pd 

df = pd.read_excel('reshaping.xlsx ')

df

   Estudante Categoria  Semana          Tópico  Nota
0      Maria    Testes       1       1. Python   100
1      Maria   Projeto       1       1. Python   100
2      Maria    Testes       1       2. GitHub    70
3      Maria   Projeto       1       2. GitHub    70
4      Maria    Testes       2   3. Matplotlib    80
5      Maria   Projeto       2   3. Matplotlib    70
6      Maria    Testes       2          4. SQL    80
7      Maria   Projeto       2          4. SQL    70
8      Maria    Testes       3        5. NumPy    60
9      Maria   Projeto       3        5. NumPy    60
10     Maria    Testes       3          6. POO    90
11     Maria   Projeto       3          6. POO    80
12     Maria    Testes       4       7. Pandas    70
13     Maria   Projeto       4       7. Pandas    70
14     Maria    Testes       4  8. Estatística    80
15     Maria   Projeto       4  8. Estatística    80
16      João    Testes       1       1. Python   100
17      João   Projeto       1       1. Python    80
18      João    Testes       1       2. GitHub    90
19      João   Projeto       1       2. GitHub    90
20      João    Testes       2   3. Matplotlib    60
21      João   Projeto       2   3. Matplotlib    70
22      João    Testes       2          4. SQL    70
23      João   Projeto       2          4. SQL    80
24      João    Testes       3        5. NumPy    80
25      João   Projeto       3        5. NumPy    90
26      João    Testes       3          6. POO    70
27      João   Projeto       3          6. POO    80
28      João    Testes       4       7. Pandas    70
29      João   Projeto       4       7. Pandas   100
30      João    Testes       4  8. Estatística    80
31      João   Projeto       4  8. Estatística    90

In [4]:
df.index

RangeIndex(start=0, stop=32, step=1)

In [5]:
df.columns

Index(['Estudante', 'Categoria', 'Semana', 'Tópico', 'Nota'], dtype='object')

In [8]:
df_pivot = df.pivot(index=['Estudante'], columns=['Categoria','Semana','Tópico'], values='Nota')
df_pivot

Categoria,Testes,Projeto,Testes,Projeto,Testes,Projeto,Testes,Projeto,Testes,Projeto,Testes,Projeto,Testes,Projeto,Testes,Projeto
Semana,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4
Tópico,1. Python,1. Python,2. GitHub,2. GitHub,3. Matplotlib,3. Matplotlib,4. SQL,4. SQL,5. NumPy,5. NumPy,6. POO,6. POO,7. Pandas,7. Pandas,8. Estatística,8. Estatística
Estudante,,,,,,,,,,,,,,,,
João,100,80,90,90,60,70,70,80,80,90,70,80,70,100,80,90
Maria,100,100,70,70,80,70,80,70,60,60,90,80,70,70,80,80

In [10]:
df_pivot.index

Index(['João', 'Maria'], dtype='object', name='Estudante')

In [13]:
df_pivot.columns

MultiIndex([( 'Testes', 1,      '1. Python'),
            ('Projeto', 1,      '1. Python'),
            ( 'Testes', 1,      '2. GitHub'),
            ('Projeto', 1,      '2. GitHub'),
            ( 'Testes', 2,  '3. Matplotlib'),
            ('Projeto', 2,  '3. Matplotlib'),
            ( 'Testes', 2,         '4. SQL'),
            ('Projeto', 2,         '4. SQL'),
            ( 'Testes', 3,       '5. NumPy'),
            ('Projeto', 3,       '5. NumPy'),
            ( 'Testes', 3,         '6. POO'),
            ('Projeto', 3,         '6. POO'),
            ( 'Testes', 4,      '7. Pandas'),
            ('Projeto', 4,      '7. Pandas'),
            ( 'Testes', 4, '8. Estatística'),
            ('Projeto', 4, '8. Estatística')],
           names=['Categoria', 'Semana', 'Tópico'])

In [14]:
df_pivot

Categoria,Testes,Projeto,Testes,Projeto,Testes,Projeto,Testes,Projeto,Testes,Projeto,Testes,Projeto,Testes,Projeto,Testes,Projeto
Semana,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4
Tópico,1. Python,1. Python,2. GitHub,2. GitHub,3. Matplotlib,3. Matplotlib,4. SQL,4. SQL,5. NumPy,5. NumPy,6. POO,6. POO,7. Pandas,7. Pandas,8. Estatística,8. Estatística
Estudante,,,,,,,,,,,,,,,,
João,100,80,90,90,60,70,70,80,80,90,70,80,70,100,80,90
Maria,100,100,70,70,80,70,80,70,60,60,90,80,70,70,80,80

In [16]:
df_pivot.stack(level=0)

C:\Users\Amanda Nazaré\AppData\Local\Temp\ipykernel_42356\10025394.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_pivot.stack(level=0)

Semana                      1                       2               3         \
Tópico              1. Python 2. GitHub 3. Matplotlib 4. SQL 5. NumPy 6. POO
Estudante Categoria
João      Projeto          80        90            70     80       90     80
          Testes          100        90            60     70       80     70
Maria     Projeto         100        70            70     70       60     80
          Testes          100        70            80     80       60     90

Semana                      4
Tópico              7. Pandas 8. Estatística
Estudante Categoria
João      Projeto         100             90
          Testes           70             80
Maria     Projeto          70             80
          Testes           70             80

In [17]:
df_pivot.stack(level=0).index

C:\Users\Amanda Nazaré\AppData\Local\Temp\ipykernel_42356\3153054886.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_pivot.stack(level=0).index

MultiIndex([( 'João', 'Projeto'),
            ( 'João',  'Testes'),
            ('Maria', 'Projeto'),
            ('Maria',  'Testes')],
           names=['Estudante', 'Categoria'])

In [18]:
df_pivot.stack(level=0).columns

C:\Users\Amanda Nazaré\AppData\Local\Temp\ipykernel_42356\3251203482.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_pivot.stack(level=0).columns

MultiIndex([(1,      '1. Python'),
            (1,      '2. GitHub'),
            (2,  '3. Matplotlib'),
            (2,         '4. SQL'),
            (3,       '5. NumPy'),
            (3,         '6. POO'),
            (4,      '7. Pandas'),
            (4, '8. Estatística')],
           names=['Semana', 'Tópico'])

In [19]:
df_pivot.stack(level=0)

C:\Users\Amanda Nazaré\AppData\Local\Temp\ipykernel_42356\10025394.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_pivot.stack(level=0)

Semana                      1                       2               3         \
Tópico              1. Python 2. GitHub 3. Matplotlib 4. SQL 5. NumPy 6. POO
Estudante Categoria
João      Projeto          80        90            70     80       90     80
          Testes          100        90            60     70       80     70
Maria     Projeto         100        70            70     70       60     80
          Testes          100        70            80     80       60     90

Semana                      4
Tópico              7. Pandas 8. Estatística
Estudante Categoria
João      Projeto         100             90
          Testes           70             80
Maria     Projeto          70             80
          Testes           70             80

In [22]:
df_pivot.stack(level=0).unstack(level=0)

C:\Users\Amanda Nazaré\AppData\Local\Temp\ipykernel_42356\1451058433.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_pivot.stack(level=0).unstack(level=0)

Semana            1                                   2                     \
Tópico    1. Python       2. GitHub       3. Matplotlib       4. SQL
Estudante      João Maria      João Maria          João Maria   João Maria
Categoria
Projeto          80   100        90    70            70    70     80    70
Testes          100   100        90    70            60    80     70    80

Semana           3                            4
Tópico    5. NumPy       6. POO       7. Pandas       8. Estatística
Estudante     João Maria   João Maria      João Maria           João Maria
Categoria
Projeto         90    60     80    80       100    70             90    80
Testes          80    60     70    90        70    70             80    80

In [23]:
df.pivot(index=['Estudante'], columns=['Categoria','Semana','Tópico'], values='Nota')

Categoria,Testes,Projeto,Testes,Projeto,Testes,Projeto,Testes,Projeto,Testes,Projeto,Testes,Projeto,Testes,Projeto,Testes,Projeto
Semana,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4
Tópico,1. Python,1. Python,2. GitHub,2. GitHub,3. Matplotlib,3. Matplotlib,4. SQL,4. SQL,5. NumPy,5. NumPy,6. POO,6. POO,7. Pandas,7. Pandas,8. Estatística,8. Estatística
Estudante,,,,,,,,,,,,,,,,
João,100,80,90,90,60,70,70,80,80,90,70,80,70,100,80,90
Maria,100,100,70,70,80,70,80,70,60,60,90,80,70,70,80,80

In [25]:
df.pivot_table(index=['Estudante'], columns=['Semana','Tópico'], values='Nota')

Semana            1                       2               3                4  \
Tópico    1. Python 2. GitHub 3. Matplotlib 4. SQL 5. NumPy 6. POO 7. Pandas
Estudante
João           90.0      90.0          65.0   75.0     85.0   75.0      85.0
Maria         100.0      70.0          75.0   75.0     60.0   85.0      70.0

Semana
Tópico    8. Estatística
Estudante
João                85.0
Maria               80.0

In [26]:
df.pivot_table(index=['Estudante'], columns=['Semana','Tópico'], values='Nota', aggfunc='count')

Semana            1                       2               3                4  \
Tópico    1. Python 2. GitHub 3. Matplotlib 4. SQL 5. NumPy 6. POO 7. Pandas
Estudante
João              2         2             2      2        2      2         2
Maria             2         2             2      2        2      2         2

Semana
Tópico    8. Estatística
Estudante
João                   2
Maria                  2

In [27]:
df.pivot_table(index=['Estudante'], columns=['Semana','Tópico'], values='Nota', aggfunc='sum')

Semana            1                       2               3                4  \
Tópico    1. Python 2. GitHub 3. Matplotlib 4. SQL 5. NumPy 6. POO 7. Pandas
Estudante
João            180       180           130    150      170    150       170
Maria           200       140           150    150      120    170       140

Semana
Tópico    8. Estatística
Estudante
João                 170
Maria                160

In [28]:
df.pivot_table(index=['Estudante'], columns=['Semana','Tópico'], values='Nota')

Semana            1                       2               3                4  \
Tópico    1. Python 2. GitHub 3. Matplotlib 4. SQL 5. NumPy 6. POO 7. Pandas
Estudante
João           90.0      90.0          65.0   75.0     85.0   75.0      85.0
Maria         100.0      70.0          75.0   75.0     60.0   85.0      70.0

Semana
Tópico    8. Estatística
Estudante
João                85.0
Maria               80.0

In [30]:
df.groupby(['Estudante','Semana','Tópico'])['Nota'].mean()

Estudante  Semana  Tópico
João       1       1. Python          90.0
                   2. GitHub          90.0
           2       3. Matplotlib      65.0
                   4. SQL             75.0
           3       5. NumPy           85.0
                   6. POO             75.0
           4       7. Pandas          85.0
                   8. Estatística     85.0
Maria      1       1. Python         100.0
                   2. GitHub          70.0
           2       3. Matplotlib      75.0
                   4. SQL             75.0
           3       5. NumPy           60.0
                   6. POO             85.0
           4       7. Pandas          70.0
                   8. Estatística     80.0
Name: Nota, dtype: float64