In [124]:
import pandas as pd
import numpy as np

df_vendas = pd.read_csv("vendas_tech.csv")
display(df_vendas)
df_gerentes = pd.read_excel("gerentes_lojas.xlsx")
display(df_gerentes)

C:\Users\Amanda Nazaré\AppData\Local\Temp\ipykernel_7544\2014732352.py:4: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_vendas = pd.read_csv("vendas_tech.csv")

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

In [125]:
#inspeção
display(df_vendas)
display(df_vendas.head(15))
display(df_vendas.tail(6))
display(df_vendas.sample(8))
display(df_vendas.shape)
display(list(df_vendas.columns))
display(df_vendas.info())
display(df_vendas.describe())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809,NaN
6,7,2024-12-08,Salvador,"Monitor 27""",1200.0,1,Cliente_11076,NaN
7,8,2024-09-12,São Paulo,"Monitor 27""",1200.0,2,Cliente_14053,NaN
8,9,2023-05-20,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_19175,NaN
9,10,2024-10-16,Recife,Notebook HP,3200.0,1,Cliente_13508,NaN
10,11,2023-06-28,RIO DE JANEIRO,Smartphone Samsung,2200.0,1,Cliente_3253,NaN
11,12,2024-01-29,Rio de Janeiro,Mouse Gamer,120.0,1,Cliente_586,NaN
12,13,2024-06-25,Recife,Smartphone Samsung,2200.0,1,Cliente_4301,NaN
13,14,2023-04-13,Belo Horizonte,Smartphone Samsung,2200.0,1,Cliente_22985,NaN
14,15,2023-06-23,Curitiba,Cabo HDMI,40.0,1,Cliente_27383,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
100094,32853,2024-04-10,Salvador,Smartphone Samsung,2200.0,2,Cliente_29799,NaN
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
10868,10869,2023-02-18,RIO DE JANEIRO,Teclado Mecânico,250.0,1,Cliente_26809,NaN
29403,29404,2024-10-06,Porto Alegre,Mouse Gamer,120.0,1,Cliente_12464,NaN
36374,36375,2024-05-22,Porto Alegre,Smartphone Samsung,2200.0,2,Cliente_17502,NaN
58770,58771,2024-04-01,Recife,Mouse Gamer,120.0,1,Cliente_2856,NaN
58605,58606,2023-10-02,Belo Horizonte,Smartphone Samsung,2200.0,1,Cliente_16361,NaN
61772,61773,2024-08-26,Belo Horizonte,iPhone 14,5500.0,1,Cliente_25481,NaN
93454,93455,2023-10-23,Salvador,"Monitor 27""",1200.0,1,Cliente_22281,NaN
44977,44978,2023-06-21,Rio de Janeiro,Mouse Gamer,120.0,1,Cliente_5265,NaN

(100100, 8)

['ID_Pedido',
 'Data',
 'Loja',
 'Produto',
 'Preco_Unitario',
 'Qtd',
 'Cliente',
 'Data_Base']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  object
 2   Loja            98099 non-null   object
 3   Produto         100100 non-null  object
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  object
 7   Data_Base       1 non-null       object
dtypes: float64(1), int64(2), object(5)
memory usage: 6.1+ MB

None

           ID_Pedido  Preco_Unitario            Qtd
count  100100.000000   100100.000000  100100.000000
mean    50004.810180     2000.204595       1.499101
std     28866.872543     1841.050733       1.241605
min         1.000000       40.000000       1.000000
25%     25008.750000      120.000000       1.000000
50%     50004.500000     1200.000000       1.000000
75%     75002.250000     3200.000000       1.000000
max    100000.000000     5500.000000      10.000000

In [126]:
#tratamento de dados
display(df_vendas["Loja"])
display(df_vendas[["Loja","Cliente"]])

# colunas
df_analise = df_vendas.drop(columns=["Data_Base"])

# nulos
df_analise["Loja"] = df_analise["Loja"].fillna("online")

#Tipos de dados
df_analise["Data"] = pd.to_datetime(df_analise["Data"], format="%Y-%m-%d")

#padronização
df_analise["Loja"] = df_analise["Loja"].str.strip()
df_analise["Loja"] = df_analise["Loja"].str.title()

df_gerentes["Loja"] = df_gerentes["Loja"].str.strip()
df_gerentes["Loja"] = df_gerentes["Loja"].str.title()

#duplicatas
df_analise = df_analise.drop_duplicates(subset=["ID_Pedido"], keep="last")


display(df_analise)
display(df_analise.info())

0              São Paulo
1         Belo Horizonte
2                    NaN
3         RIO DE JANEIRO
4         Rio de Janeiro
               ...
100095      Porto Alegre
100096      Porto Alegre
100097    Belo Horizonte
100098          Salvador
100099        São Paulo
Name: Loja, Length: 100100, dtype: object

                  Loja        Cliente
0            São Paulo   Cliente_4095
1       Belo Horizonte   Cliente_8750
2                  NaN  Cliente_14859
3       RIO DE JANEIRO  Cliente_17343
4       Rio de Janeiro  Cliente_23377
...                ...            ...
100095    Porto Alegre  Cliente_11755
100096    Porto Alegre  Cliente_12879
100097  Belo Horizonte   Cliente_8160
100098        Salvador  Cliente_28545
100099      São Paulo    Cliente_3274

[100100 rows x 2 columns]

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 100099
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100000 non-null  int64
 1   Data            100000 non-null  datetime64[ns]
 2   Loja            100000 non-null  object
 3   Produto         100000 non-null  object
 4   Preco_Unitario  100000 non-null  float64
 5   Qtd             100000 non-null  int64
 6   Cliente         100000 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 6.1+ MB

None

In [127]:
# #criar novas colunas

# #faturamento
df_analise["Faturamento"] = df_analise["Qtd"] * df_analise["Preco_Unitario"]
#região

# # forma de venda
df_analise["Forma_de_Venda"] = np.where(df_analise["Loja"] =="Online", "Online", "Presencial")
#região

def definir_regioes(loja):
    dic_regioes = {
        'São Paulo': "Sudeste", 
        'Belo Horizonte': "Sudeste", 
        'Online':"Online", 
        'Rio De Janeiro':"Rio de Janeiro",
        'Salvador':"Nordeste", 
        'Recife':"Nordeste", 
        'Curitiba':"Sul", 
        'Porto Alegre':"Sul"
    }
    return dic_regioes[loja]
df_analise["Região"] = df_analise["Loja"].map(definir_regioes)

display(df_analise)
display(df_analise.isna().sum())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Região
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial,Sudeste
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Rio de Janeiro
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial,Rio de Janeiro
...,...,...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,5500.0,Presencial,Sul
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,7000.0,Presencial,Sul
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,4400.0,Presencial,Sudeste
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,11000.0,Presencial,Nordeste
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,6400.0,Presencial,Sudeste

ID_Pedido         0
Data              0
Loja              0
Produto           0
Preco_Unitario    0
Qtd               0
Cliente           0
Faturamento       0
Forma_de_Venda    0
Região            0
dtype: int64

In [128]:
#analisar -> filtar
df_analise = df_analise.sort_values(by=["Data","Faturamento"], ascending=False)
df_analise = df_analise.reset_index(drop=True)
#loc: id do pedido -> por nome da coluna e por nome da linha
id_pedido = 4
loja = df_analise.loc[df_analise["ID_Pedido"]==4, "Loja"].values[0]
produto = df_analise.loc[df_analise["ID_Pedido"]==4,"Produto"].values[0]
cliente = df_analise.loc[df_analise["ID_Pedido"]==4,"Cliente"].values[0]
print(loja,produto, cliente)

#i.loc -> por posicao
id_pedido = 4
loja = df_analise.iloc[3,2]
produto = df_analise.iloc[3,3]
cliente = df_analise.iloc[3,6]
print(loja, produto, cliente)


#exportar pedaços de base
df_vendas_sp = df_analise[df_analise["Loja"]=="São Paulo"]
df_vendas_sp.to_csv("Vendas_SP.csv", index=False)
display(df_vendas_sp)

# exportar as vendas de 2024
df_vendas_2024 = df_analise[df_analise["Data"].dt.year==2024]
display(df_vendas_2024)

#duplas condições
condicao = df_analise["Produto"]=="Cabo HDMI"
condicao2 = df_analise["Região"]=="Sul"
df_vendas_HDMI_SUL = df_analise[condicao & condicao2]
display(df_vendas_HDMI_SUL)
#condicional
df_id_pedido_4 = df_analise[df_analise["ID_Pedido"]==4]
display(df_id_pedido_4)

#exportar pedaços da vase
df_vendas_sp = df_analise
display(df_analise)

Rio De Janeiro Mouse Gamer Cliente_17343
Recife Notebook Dell Cliente_11509

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Região
6,177,2024-12-30,São Paulo,Smartphone Samsung,2200.0,3,Cliente_4388,6600.0,Presencial,Sudeste
8,7446,2024-12-30,São Paulo,iPhone 14,5500.0,1,Cliente_1302,5500.0,Presencial,Sudeste
15,60640,2024-12-30,São Paulo,iPhone 14,5500.0,1,Cliente_13172,5500.0,Presencial,Sudeste
20,77621,2024-12-30,São Paulo,iPhone 14,5500.0,1,Cliente_19106,5500.0,Presencial,Sudeste
21,91693,2024-12-30,São Paulo,iPhone 14,5500.0,1,Cliente_17362,5500.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
99960,53171,2023-01-01,São Paulo,Teclado Mecânico,250.0,1,Cliente_19747,250.0,Presencial,Sudeste
99962,59136,2023-01-01,São Paulo,Teclado Mecânico,250.0,1,Cliente_14239,250.0,Presencial,Sudeste
99978,39483,2023-01-01,São Paulo,Mouse Gamer,120.0,1,Cliente_1274,120.0,Presencial,Sudeste
99979,48375,2023-01-01,São Paulo,Mouse Gamer,120.0,1,Cliente_1544,120.0,Presencial,Sudeste
99982,90270,2023-01-01,São Paulo,Mouse Gamer,120.0,1,Cliente_6418,120.0,Presencial,Sudeste

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Região
0,35192,2024-12-30,Salvador,iPhone 14,5500.0,2,Cliente_7615,11000.0,Presencial,Nordeste
1,60794,2024-12-30,Rio De Janeiro,Smartphone Samsung,2200.0,5,Cliente_9964,11000.0,Presencial,Rio de Janeiro
2,86379,2024-12-30,Salvador,iPhone 14,5500.0,2,Cliente_25166,11000.0,Presencial,Nordeste
3,40137,2024-12-30,Recife,Notebook Dell,3500.0,2,Cliente_11509,7000.0,Presencial,Nordeste
4,43207,2024-12-30,Belo Horizonte,Notebook Dell,3500.0,2,Cliente_15893,7000.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
49572,80685,2024-01-01,Salvador,Cabo HDMI,40.0,1,Cliente_27122,40.0,Presencial,Nordeste
49573,83656,2024-01-01,Salvador,Cabo HDMI,40.0,1,Cliente_15422,40.0,Presencial,Nordeste
49574,85554,2024-01-01,Belo Horizonte,Cabo HDMI,40.0,1,Cliente_29280,40.0,Presencial,Sudeste
49575,88442,2024-01-01,Recife,Cabo HDMI,40.0,1,Cliente_2801,40.0,Presencial,Nordeste
49576,96813,2024-01-01,Recife,Cabo HDMI,40.0,1,Cliente_24891,40.0,Presencial,Nordeste

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Região
117,35127,2024-12-30,Curitiba,Cabo HDMI,40.0,2,Cliente_20687,80.0,Presencial,Sul
118,47774,2024-12-30,Porto Alegre,Cabo HDMI,40.0,2,Cliente_14363,80.0,Presencial,Sul
119,64473,2024-12-30,Porto Alegre,Cabo HDMI,40.0,2,Cliente_11598,80.0,Presencial,Sul
125,75695,2024-12-30,Porto Alegre,Cabo HDMI,40.0,1,Cliente_29587,40.0,Presencial,Sul
126,78584,2024-12-30,Curitiba,Cabo HDMI,40.0,1,Cliente_21307,40.0,Presencial,Sul
...,...,...,...,...,...,...,...,...,...,...
99987,35599,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_18680,40.0,Presencial,Sul
99988,37130,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_22886,40.0,Presencial,Sul
99989,49140,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_24445,40.0,Presencial,Sul
99994,70138,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_9348,40.0,Presencial,Sul
99999,97659,2023-01-01,Curitiba,Cabo HDMI,40.0,1,Cliente_58,40.0,Presencial,Sul

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Região
5832,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Rio de Janeiro

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Região
0,35192,2024-12-30,Salvador,iPhone 14,5500.0,2,Cliente_7615,11000.0,Presencial,Nordeste
1,60794,2024-12-30,Rio De Janeiro,Smartphone Samsung,2200.0,5,Cliente_9964,11000.0,Presencial,Rio de Janeiro
2,86379,2024-12-30,Salvador,iPhone 14,5500.0,2,Cliente_25166,11000.0,Presencial,Nordeste
3,40137,2024-12-30,Recife,Notebook Dell,3500.0,2,Cliente_11509,7000.0,Presencial,Nordeste
4,43207,2024-12-30,Belo Horizonte,Notebook Dell,3500.0,2,Cliente_15893,7000.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
99995,88109,2023-01-01,Salvador,Cabo HDMI,40.0,1,Cliente_22054,40.0,Presencial,Nordeste
99996,91765,2023-01-01,Salvador,Cabo HDMI,40.0,1,Cliente_1746,40.0,Presencial,Nordeste
99997,93303,2023-01-01,Belo Horizonte,Cabo HDMI,40.0,1,Cliente_11142,40.0,Presencial,Sudeste
99998,95393,2023-01-01,Salvador,Cabo HDMI,40.0,1,Cliente_23137,40.0,Presencial,Nordeste
99999,97659,2023-01-01,Curitiba,Cabo HDMI,40.0,1,Cliente_58,40.0,Presencial,Sul

In [129]:
#analises por agrupamento
# display(df_analise)

#ranking de faturamento por loja
analise_lojas = df_analise[["Loja", "Faturamento"]].groupby("Loja").sum()
display(analise_lojas)

#ranking de protudos que mais venderam no online
df_vendas_online = df_analise[df_analise["Loja"]=="Online"]
analise_produtos_online = df_vendas_online[["Produto", "Qtd"]].groupby("Produto").sum()
analise_produtos_online = analise_produtos_online.sort_values(by="Qtd", ascending=False)
analise_produtos_online = analise_produtos_online.rename(columns={"Qtd":"Vendas Totais"})
display(analise_produtos_online)

#quais lojas mais venderam os produtos
analise_lojas_em_produtos = df_analise[["Loja","Produto","Qtd"]].groupby(["Produto","Loja"]).sum()

#analise de ranking por loja e produto
#quais produtos venderam mais em cada uma das lojas
analise_produtos_em_lojas = df_analise[["Loja", "Produto", "Qtd"]].groupby(["Loja", "Produto"]).sum()
with pd.option_context("display.max_rows", None):
    display(analise_produtos_em_lojas)
    display(analise_lojas_em_produtos)

                Faturamento
Loja
Belo Horizonte   41714890.0
Curitiba         41121720.0
Online            6080850.0
Porto Alegre     41678460.0
Recife           42190390.0
Rio De Janeiro   42294720.0
Salvador         42300610.0
São Paulo        42090690.0

                    Vendas Totais
Produto
Notebook HP                   442
Cabo HDMI                     403
iPhone 14                     390
Mouse Gamer                   379
Notebook Dell                 369
Teclado Mecânico              343
Monitor 27"                   332
Smartphone Samsung            311

                                    Qtd
Loja           Produto
Belo Horizonte Cabo HDMI           2636
               Monitor 27"         2625
               Mouse Gamer         2465
               Notebook Dell       2654
               Notebook HP         2775
               Smartphone Samsung  2597
               Teclado Mecânico    2609
               iPhone 14           2478
Curitiba       Cabo HDMI           2698
               Monitor 27"         2626
               Mouse Gamer         2600
               Notebook Dell       2517
               Notebook HP         2529
               Smartphone Samsung  2444
               Teclado Mecânico    2742
               iPhone 14           2652
Online         Cabo HDMI            403
               Monitor 27"          332
               Mouse Gamer          379
               Notebook Dell        369
               Notebook HP          442
               Smartphone Samsung   311
               Teclado Mecânico     343
               iPhone 14            390
Porto Alegre   Cabo HDMI           2571
               Monitor 27"         2655
               Mouse Gamer         2611
               Notebook Dell       2770
               Notebook HP         2511
               Smartphone Samsung  2603
               Teclado Mecânico    2598
               iPhone 14           2540
Recife         Cabo HDMI           2534
               Monitor 27"         2647
               Mouse Gamer         2639
               Notebook Dell       2566
               Notebook HP         2651
               Smartphone Samsung  2660
               Teclado Mecânico    2775
               iPhone 14           2652
Rio De Janeiro Cabo HDMI           2747
               Monitor 27"         2798
               Mouse Gamer         2652
               Notebook Dell       2534
               Notebook HP         2614
               Smartphone Samsung  2626
               Teclado Mecânico    2548
               iPhone 14           2702
Salvador       Cabo HDMI           2566
               Monitor 27"         2545
               Mouse Gamer         2711
               Notebook Dell       2512
               Notebook HP         2785
               Smartphone Samsung  2627
               Teclado Mecânico    2579
               iPhone 14           2671
São Paulo      Cabo HDMI           2649
               Monitor 27"         2796
               Mouse Gamer         2714
               Notebook Dell       2535
               Notebook HP         2592
               Smartphone Samsung  2476
               Teclado Mecânico    2589
               iPhone 14           2735

                                    Qtd
Produto            Loja
Cabo HDMI          Belo Horizonte  2636
                   Curitiba        2698
                   Online           403
                   Porto Alegre    2571
                   Recife          2534
                   Rio De Janeiro  2747
                   Salvador        2566
                   São Paulo       2649
Monitor 27"        Belo Horizonte  2625
                   Curitiba        2626
                   Online           332
                   Porto Alegre    2655
                   Recife          2647
                   Rio De Janeiro  2798
                   Salvador        2545
                   São Paulo       2796
Mouse Gamer        Belo Horizonte  2465
                   Curitiba        2600
                   Online           379
                   Porto Alegre    2611
                   Recife          2639
                   Rio De Janeiro  2652
                   Salvador        2711
                   São Paulo       2714
Notebook Dell      Belo Horizonte  2654
                   Curitiba        2517
                   Online           369
                   Porto Alegre    2770
                   Recife          2566
                   Rio De Janeiro  2534
                   Salvador        2512
                   São Paulo       2535
Notebook HP        Belo Horizonte  2775
                   Curitiba        2529
                   Online           442
                   Porto Alegre    2511
                   Recife          2651
                   Rio De Janeiro  2614
                   Salvador        2785
                   São Paulo       2592
Smartphone Samsung Belo Horizonte  2597
                   Curitiba        2444
                   Online           311
                   Porto Alegre    2603
                   Recife          2660
                   Rio De Janeiro  2626
                   Salvador        2627
                   São Paulo       2476
Teclado Mecânico   Belo Horizonte  2609
                   Curitiba        2742
                   Online           343
                   Porto Alegre    2598
                   Recife          2775
                   Rio De Janeiro  2548
                   Salvador        2579
                   São Paulo       2589
iPhone 14          Belo Horizonte  2478
                   Curitiba        2652
                   Online           390
                   Porto Alegre    2540
                   Recife          2652
                   Rio De Janeiro  2702
                   Salvador        2671
                   São Paulo       2735

In [130]:
display(df_analise.head())

#quais gerente bateram a meta em janeiro de 2023
df_meta = df_analise[(df_analise["Data"].dt.year==2023) & (df_analise["Data"].dt.month==1)]

df_meta = df_meta[["Loja","Faturamento"]].groupby("Loja", as_index=False).sum()
df_meta = df_meta.merge(df_gerentes, on="Loja", how="left")
df_meta["Bateu Meta"] = np.where(df_meta["Faturamento"] >= df_meta["Meta_Mensal"],"Sim","Não")
display(df_meta)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Região
0,35192,2024-12-30,Salvador,iPhone 14,5500.0,2,Cliente_7615,11000.0,Presencial,Nordeste
1,60794,2024-12-30,Rio De Janeiro,Smartphone Samsung,2200.0,5,Cliente_9964,11000.0,Presencial,Rio de Janeiro
2,86379,2024-12-30,Salvador,iPhone 14,5500.0,2,Cliente_25166,11000.0,Presencial,Nordeste
3,40137,2024-12-30,Recife,Notebook Dell,3500.0,2,Cliente_11509,7000.0,Presencial,Nordeste
4,43207,2024-12-30,Belo Horizonte,Notebook Dell,3500.0,2,Cliente_15893,7000.0,Presencial,Sudeste

             Loja  Faturamento   Gerente  Meta_Mensal Bateu Meta
0  Belo Horizonte    1779100.0   Juliana      55000.0        Sim
1        Curitiba    1986920.0   Roberto      45000.0        Sim
2          Online     404570.0       NaN          NaN        Não
3    Porto Alegre    1726640.0     Pedro      42000.0        Sim
4          Recife    1779020.0    Marcos      48000.0        Sim
5  Rio De Janeiro    1736830.0  Fernanda      60000.0        Sim
6        Salvador    1686070.0       Ana      52000.0        Sim
7       São Paulo    1831140.0    Carlos      50000.0        Sim