In [21]:
import pandas as pd

In [22]:
df_csv = pd.read_csv('cereal.csv')
df_csv.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843

In [23]:
df_csv.tail()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [24]:
df_excel = pd.read_excel('cereal.xlsx')
df_excel.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843

In [25]:
df_excel.tail()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [27]:
dados_digimon = {
    'Digiescolhido': ['Tai', 'Matt', 'Sora', 'Izzy', 'Mimi', 'Joe', 'T.K.', 'Kari'],
    'Digimon': ['Agumon', 'Gabumon', 'Biyomon', 'Tentomon', 'Palmon', 'Gomamon', 'Patamon', 'Gatomon'],
    'Brasao': ['Coragem', 'Amizade', 'Amor', 'Sabedoria', 'Sinceridade', 'Confiabilidade', 'Esperanca', 'Luz'],
    'Nivel_Maximo': ['Mega (WarGreymon)', 'Mega (MetalGarurumon)', 'Perfeito (Garudamon)', 'Perfeito (MegaKabuterimon)', 'Perfeito (Lillymon)', 'Perfeito (Zudomon)', 'Perfeito (MagnaAngemon)', 'Perfeito (Angewomon)']
}

df_dicionario = pd.DataFrame(dados_digimon)
df_dicionario

  Digiescolhido   Digimon          Brasao                Nivel_Maximo
0           Tai    Agumon         Coragem           Mega (WarGreymon)
1          Matt   Gabumon         Amizade       Mega (MetalGarurumon)
2          Sora   Biyomon            Amor        Perfeito (Garudamon)
3          Izzy  Tentomon       Sabedoria  Perfeito (MegaKabuterimon)
4          Mimi    Palmon     Sinceridade         Perfeito (Lillymon)
5           Joe   Gomamon  Confiabilidade          Perfeito (Zudomon)
6          T.K.   Patamon       Esperanca     Perfeito (MagnaAngemon)
7          Kari   Gatomon             Luz        Perfeito (Angewomon)

In [28]:
dados_digimon_s2 = {
    'Digiescolhido': ['Davis', 'Yolei', 'Cody', 'T.K.', 'Kari', 'Ken'],
    'Digimon': ['Veemon', 'Hawkmon', 'Armadillomon', 'Patamon', 'Gatomon', 'Wormmon'],
    'Brasao': ['Coragem/Amizade', 'Amor/Sinceridade', 'Confiabilidade/Sabedoria', 'Esperanca', 'Luz', 'Bondade'],
    'Nivel_Maximo': ['Mega (Imperialdramon)', 'Perfeito (Silphymon)', 'Perfeito (Shakkoumon)', 'Perfeito (MagnaAngemon)', 'Perfeito (Angewomon)', 'Mega (Imperialdramon)']
}

df_dicionario_2 = pd.DataFrame(dados_digimon_s2)
df_dicionario_2

,Digiescolhido,Digimon,Brasao,Nivel_Maximo
0,Davis,Veemon,Coragem/Amizade,Mega (Imperialdramon)
1,Yolei,Hawkmon,Amor/Sinceridade,Perfeito (Silphymon)
2,Cody,Armadillomon,Confiabilidade/Sabedoria,Perfeito (Shakkoumon)
3,T.K.,Patamon,Esperanca,Perfeito (MagnaAngemon)
4,Kari,Gatomon,Luz,Perfeito (Angewomon)
5,Ken,Wormmon,Bondade,Mega (Imperialdramon)

In [30]:
df_digi_escolhidos = pd.concat([df_dicionario,df_dicionario_2], ignore_index=True)
df_digi_escolhidos

,Digiescolhido,Digimon,Brasao,Nivel_Maximo
0,Tai,Agumon,Coragem,Mega (WarGreymon)
1,Matt,Gabumon,Amizade,Mega (MetalGarurumon)
2,Sora,Biyomon,Amor,Perfeito (Garudamon)
3,Izzy,Tentomon,Sabedoria,Perfeito (MegaKabuterimon)
4,Mimi,Palmon,Sinceridade,Perfeito (Lillymon)
5,Joe,Gomamon,Confiabilidade,Perfeito (Zudomon)
6,T.K.,Patamon,Esperanca,Perfeito (MagnaAngemon)
7,Kari,Gatomon,Luz,Perfeito (Angewomon)
8,Davis,Veemon,Coragem/Amizade,Mega (Imperialdramon)
9,Yolei,Hawkmon,Amor/Sinceridade,Perfeito (Silphymon)
10,Cody,Armadillomon,Confiabilidade/Sabedoria,Perfeito (Shakkoumon)
11,T.K.,Patamon,Esperanca,Perfeito (MagnaAngemon)
12,Kari,Gatomon,Luz,Perfeito (Angewomon)
13,Ken,Wormmon,Bondade,Mega (Imperialdramon)

In [ ]:
import numpy as np

função = ['defesa', 'ataque', 'suporte']
personagem = ['Tai', 'Matt', 'Sora', 'Izzy', 'Mimi', 'Joe', 'T.K.', 'Kari','Davis', 'Yolei', 'Cody','Ken']
df_digi_escolhidos = {
    'Digiescolhido' : np.random.choice(personagem,6),
    'Função': np.random.choice(função,6)
}

df_dados= pd.DataFrame(df_digi_escolhidos)
df_dados

  Digiescolhido   Função
0         Yolei   ataque
1          Kari   ataque
2          Matt   ataque
3          Mimi  suporte
4          Sora  suporte
5          Kari   defesa

In [40]:
funcionarios = {
    'id': ['FTI1', 'FVE2', 'FRH1', 'FVE1'],
    'Nome': ['João Silva', 'Maria Souza', 'José Ramos', 'Pedro Ferreira'],
    'Idade': [35, 40, 54, 39],
    'Tempo de Empresa': [3, 10, 15, 7],
}

df_funcionarios = pd.DataFrame(funcionarios)
df_funcionarios

     id            Nome  Idade  Tempo de Empresa
0  FTI1      João Silva     35                 3
1  FVE2     Maria Souza     40                10
2  FRH1      José Ramos     54                15
3  FVE1  Pedro Ferreira     39                 7

In [41]:
dados_funcionarios = {
    'id': ['FVE1', 'FRH1', 'FTI1', 'FVE2'],
    'Setor': ['Vendas', 'RH', 'TI', 'Vendas'],
    'Salario': np.random.randint(2000, 10000, size=4),
}

df_dados_funcionarios = pd.DataFrame(dados_funcionarios)
df_dados_funcionarios

     id   Setor  Salario
0  FVE1  Vendas     4197
1  FRH1      RH     2222
2  FTI1      TI     6158
3  FVE2  Vendas     4076

In [43]:
df_funcionarios_completo = pd.merge(df_funcionarios,df_dados_funcionarios, on='id')
df_funcionarios_completo

     id            Nome  Idade  Tempo de Empresa   Setor  Salario
0  FTI1      João Silva     35                 3      TI     6158
1  FVE2     Maria Souza     40                10  Vendas     4076
2  FRH1      José Ramos     54                15      RH     2222
3  FVE1  Pedro Ferreira     39                 7  Vendas     4197