In [15]:
import pandas as pd
BASE = 'dados_transacoes.csv'

df = pd.read_csv(BASE)

df.head()

,id_cliente,data_transação,categoria_produto,idade,genero,preco,quantidade
0,fb3e7183-2f2b-49f0-b6fc-7bb82f62ab66,01/01/2024,Eletrônicos,56,Masculino,3077.35,1
1,554138dc-b472-4420-9e50-46fe24262598,11/01/2024,Eletrônicos,69,Masculino,3937.89,1
2,69361fcc-d6ea-44ed-9511-4d08cb5d5ec5,29/02/2024,Alimentos,46,Feminino,8.15,3
3,119a726d-e9f5-4ebc-bd72-c10e332182a0,10/04/2024,Roupas,32,Feminino,150.71,3
4,b48da9ae-f9a5-4866-a977-30571fc8496d,15/02/2024,Roupas,60,Feminino,103.89,4

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_cliente         50000 non-null  object
 1   data_transação     50000 non-null  object
 2   categoria_produto  50000 non-null  object
 3   idade              50000 non-null  int64
 4   genero             50000 non-null  object
 5   preco              50000 non-null  float64
 6   quantidade         50000 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 2.7+ MB

In [ ]:
%%timeit

for i in range(len(df)):
    df.loc[i, 'total_for'] = df.loc[i, 'quantidade'] * df.loc[i, 'preco']

In [18]:
df.head()

,id_cliente,data_transação,categoria_produto,idade,genero,preco,quantidade
0,fb3e7183-2f2b-49f0-b6fc-7bb82f62ab66,01/01/2024,Eletrônicos,56,Masculino,3077.35,1
1,554138dc-b472-4420-9e50-46fe24262598,11/01/2024,Eletrônicos,69,Masculino,3937.89,1
2,69361fcc-d6ea-44ed-9511-4d08cb5d5ec5,29/02/2024,Alimentos,46,Feminino,8.15,3
3,119a726d-e9f5-4ebc-bd72-c10e332182a0,10/04/2024,Roupas,32,Feminino,150.71,3
4,b48da9ae-f9a5-4866-a977-30571fc8496d,15/02/2024,Roupas,60,Feminino,103.89,4

In [19]:
%%timeit

df['total_apply'] = df.apply(
    lambda linha: linha['quantidade'] * linha['preco'], axis=1
)

266 ms ± 37.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [20]:
df['preco']

0        3077.35
1        3937.89
2           8.15
3         150.71
4         103.89
          ...
49995    1223.14
49996      83.29
49997      85.85
49998    1482.96
49999      44.13
Name: preco, Length: 50000, dtype: float64

In [21]:
type(df['preco'])

pandas.core.series.Series

In [22]:
%%timeit

df['total_vetorizado'] = df['quantidade'] * df['preco']

284 μs ± 69.6 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [23]:
df['categoria_produto'].unique()

array(['Eletrônicos', 'Alimentos', 'Roupas', 'Casa & Cozinha', 'Livros'],
      dtype=object)

In [25]:
descontos_categorias = {
    'Eletrônicos':0.1,
    'Alimentos':0.05,
    'Roupas':0.15,
    'Casa & Cozinha':0.2,
    'Livros':0.25
}

In [26]:
df['categoria_produto'].map(descontos_categorias)

0        0.10
1        0.10
2        0.05
3        0.15
4        0.15
         ...
49995    0.20
49996    0.25
49997    0.25
49998    0.20
49999    0.25
Name: categoria_produto, Length: 50000, dtype: float64

In [27]:
df['categoria_produto']

0           Eletrônicos
1           Eletrônicos
2             Alimentos
3                Roupas
4                Roupas
              ...
49995    Casa & Cozinha
49996            Livros
49997            Livros
49998    Casa & Cozinha
49999            Livros
Name: categoria_produto, Length: 50000, dtype: object

In [32]:
%%timeit

df['preco_desconto'] = df['preco'] * (1 - df['categoria_produto'].map(descontos_categorias))

3.33 ms ± 100 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [29]:
df.head()

,id_cliente,data_transação,categoria_produto,idade,genero,preco,quantidade,total_apply,total_vetorizado,preco_desconto
0,fb3e7183-2f2b-49f0-b6fc-7bb82f62ab66,01/01/2024,Eletrônicos,56,Masculino,3077.35,1,3077.35,3077.35,2769.6150
1,554138dc-b472-4420-9e50-46fe24262598,11/01/2024,Eletrônicos,69,Masculino,3937.89,1,3937.89,3937.89,3544.1010
2,69361fcc-d6ea-44ed-9511-4d08cb5d5ec5,29/02/2024,Alimentos,46,Feminino,8.15,3,24.45,24.45,7.7425
3,119a726d-e9f5-4ebc-bd72-c10e332182a0,10/04/2024,Roupas,32,Feminino,150.71,3,452.13,452.13,128.1035
4,b48da9ae-f9a5-4866-a977-30571fc8496d,15/02/2024,Roupas,60,Feminino,103.89,4,415.56,415.56,88.3065