In [18]:
import pandas as pd

BASE = "dados_satisfacao.csv"

dados = pd.read_csv(BASE)

dados

,cliente_id,satisfacao_geral_01-2024,satisfacao_geral_02-2024,satisfacao_geral_03-2024,satisfacao_produto_01-2024,satisfacao_produto_02-2024,satisfacao_produto_03-2024,satisfacao_servico_01-2024,satisfacao_servico_02-2024,satisfacao_servico_03-2024,idade,genero
0,1,4,3,4,5,4,4,3,4,4,25,F
1,2,5,2,4,4,5,4,4,2,4,35,M
2,3,3,1,3,4,3,5,3,2,5,45,F
3,4,4,4,5,3,5,5,4,5,3,28,M
4,5,4,4,4,4,3,4,3,4,4,38,F
5,6,5,2,4,4,4,5,5,4,5,48,M
6,7,3,4,5,5,4,4,4,5,4,30,F
7,8,4,4,3,4,5,3,5,4,4,40,M
8,9,5,3,4,5,4,4,4,3,5,50,F
9,10,3,4,5,4,3,5,2,3,4,32,M

In [19]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cliente_id                  10 non-null     int64
 1   satisfacao_geral_01-2024    10 non-null     int64
 2   satisfacao_geral_02-2024    10 non-null     int64
 3   satisfacao_geral_03-2024    10 non-null     int64
 4   satisfacao_produto_01-2024  10 non-null     int64
 5   satisfacao_produto_02-2024  10 non-null     int64
 6   satisfacao_produto_03-2024  10 non-null     int64
 7   satisfacao_servico_01-2024  10 non-null     int64
 8   satisfacao_servico_02-2024  10 non-null     int64
 9   satisfacao_servico_03-2024  10 non-null     int64
 10  idade                       10 non-null     int64
 11  genero                      10 non-null     object
dtypes: int64(11), object(1)
memory usage: 1.1+ KB

In [20]:
dados_melt = pd.melt(
    dados,
    id_vars=["cliente_id","idade","genero"],
    value_vars=[
        "satisfacao_geral_01-2024",
        "satisfacao_geral_02-2024",
        "satisfacao_geral_03-2024",
        "satisfacao_produto_01-2024",
        "satisfacao_produto_02-2024",
        "satisfacao_produto_03-2024",
        "satisfacao_servico_01-2024",
        "satisfacao_servico_02-2024",
        "satisfacao_servico_03-2024",
    ],
    var_name="categoria_mes",
    value_name="nota"
)

dados_melt

    cliente_id  idade genero               categoria_mes  nota
0            1     25      F    satisfacao_geral_01-2024     4
1            2     35      M    satisfacao_geral_01-2024     5
2            3     45      F    satisfacao_geral_01-2024     3
3            4     28      M    satisfacao_geral_01-2024     4
4            5     38      F    satisfacao_geral_01-2024     4
..         ...    ...    ...                         ...   ...
85           6     48      M  satisfacao_servico_03-2024     5
86           7     30      F  satisfacao_servico_03-2024     4
87           8     40      M  satisfacao_servico_03-2024     4
88           9     50      F  satisfacao_servico_03-2024     5
89          10     32      M  satisfacao_servico_03-2024     4

[90 rows x 5 columns]

In [21]:
dados_melt.head(25)

    cliente_id  idade genero             categoria_mes  nota
0            1     25      F  satisfacao_geral_01-2024     4
1            2     35      M  satisfacao_geral_01-2024     5
2            3     45      F  satisfacao_geral_01-2024     3
3            4     28      M  satisfacao_geral_01-2024     4
4            5     38      F  satisfacao_geral_01-2024     4
5            6     48      M  satisfacao_geral_01-2024     5
6            7     30      F  satisfacao_geral_01-2024     3
7            8     40      M  satisfacao_geral_01-2024     4
8            9     50      F  satisfacao_geral_01-2024     5
9           10     32      M  satisfacao_geral_01-2024     3
10           1     25      F  satisfacao_geral_02-2024     3
11           2     35      M  satisfacao_geral_02-2024     2
12           3     45      F  satisfacao_geral_02-2024     1
13           4     28      M  satisfacao_geral_02-2024     4
14           5     38      F  satisfacao_geral_02-2024     4
15           6     48      M  satisfacao_geral_02-2024     2
16           7     30      F  satisfacao_geral_02-2024     4
17           8     40      M  satisfacao_geral_02-2024     4
18           9     50      F  satisfacao_geral_02-2024     3
19          10     32      M  satisfacao_geral_02-2024     4
20           1     25      F  satisfacao_geral_03-2024     4
21           2     35      M  satisfacao_geral_03-2024     4
22           3     45      F  satisfacao_geral_03-2024     3
23           4     28      M  satisfacao_geral_03-2024     5
24           5     38      F  satisfacao_geral_03-2024     4

In [22]:
dados_melt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cliente_id     90 non-null     int64
 1   idade          90 non-null     int64
 2   genero         90 non-null     object
 3   categoria_mes  90 non-null     object
 4   nota           90 non-null     int64
dtypes: int64(3), object(2)
memory usage: 3.6+ KB

In [23]:
dados_melt[["categoria","mês"]] = dados_melt["categoria_mes"].str.rsplit("_",n=1, expand=True)

In [24]:
dados_melt
dados_melt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cliente_id     90 non-null     int64
 1   idade          90 non-null     int64
 2   genero         90 non-null     object
 3   categoria_mes  90 non-null     object
 4   nota           90 non-null     int64
 5   categoria      90 non-null     object
 6   mês            90 non-null     object
dtypes: int64(3), object(4)
memory usage: 5.1+ KB

In [26]:
dados_melt['mês'] = pd.to_datetime(dados_melt["mês"], format="%m-%Y")

dados_melt

,cliente_id,idade,genero,categoria_mes,nota,categoria,mês
0,1,25,F,satisfacao_geral_01-2024,4,satisfacao_geral,2024-01-01
1,2,35,M,satisfacao_geral_01-2024,5,satisfacao_geral,2024-01-01
2,3,45,F,satisfacao_geral_01-2024,3,satisfacao_geral,2024-01-01
3,4,28,M,satisfacao_geral_01-2024,4,satisfacao_geral,2024-01-01
4,5,38,F,satisfacao_geral_01-2024,4,satisfacao_geral,2024-01-01
...,...,...,...,...,...,...,...
85,6,48,M,satisfacao_servico_03-2024,5,satisfacao_servico,2024-03-01
86,7,30,F,satisfacao_servico_03-2024,4,satisfacao_servico,2024-03-01
87,8,40,M,satisfacao_servico_03-2024,4,satisfacao_servico,2024-03-01
88,9,50,F,satisfacao_servico_03-2024,5,satisfacao_servico,2024-03-01
89,10,32,M,satisfacao_servico_03-2024,4,satisfacao_servico,2024-03-01

In [27]:
dados_melt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cliente_id     90 non-null     int64
 1   idade          90 non-null     int64
 2   genero         90 non-null     object
 3   categoria_mes  90 non-null     object
 4   nota           90 non-null     int64
 5   categoria      90 non-null     object
 6   mês            90 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 5.1+ KB

In [28]:
dados_melt["mês"] = dados_melt["mês"].dt.month
dados_melt

,cliente_id,idade,genero,categoria_mes,nota,categoria,mês
0,1,25,F,satisfacao_geral_01-2024,4,satisfacao_geral,1
1,2,35,M,satisfacao_geral_01-2024,5,satisfacao_geral,1
2,3,45,F,satisfacao_geral_01-2024,3,satisfacao_geral,1
3,4,28,M,satisfacao_geral_01-2024,4,satisfacao_geral,1
4,5,38,F,satisfacao_geral_01-2024,4,satisfacao_geral,1
...,...,...,...,...,...,...,...
85,6,48,M,satisfacao_servico_03-2024,5,satisfacao_servico,3
86,7,30,F,satisfacao_servico_03-2024,4,satisfacao_servico,3
87,8,40,M,satisfacao_servico_03-2024,4,satisfacao_servico,3
88,9,50,F,satisfacao_servico_03-2024,5,satisfacao_servico,3
89,10,32,M,satisfacao_servico_03-2024,4,satisfacao_servico,3

In [29]:
dados_melt["genero"] = dados_melt["genero"].astype("category")
dados_melt["categoria"] = dados_melt["categoria"].astype("category")
dados_melt

,cliente_id,idade,genero,categoria_mes,nota,categoria,mês
0,1,25,F,satisfacao_geral_01-2024,4,satisfacao_geral,1
1,2,35,M,satisfacao_geral_01-2024,5,satisfacao_geral,1
2,3,45,F,satisfacao_geral_01-2024,3,satisfacao_geral,1
3,4,28,M,satisfacao_geral_01-2024,4,satisfacao_geral,1
4,5,38,F,satisfacao_geral_01-2024,4,satisfacao_geral,1
...,...,...,...,...,...,...,...
85,6,48,M,satisfacao_servico_03-2024,5,satisfacao_servico,3
86,7,30,F,satisfacao_servico_03-2024,4,satisfacao_servico,3
87,8,40,M,satisfacao_servico_03-2024,4,satisfacao_servico,3
88,9,50,F,satisfacao_servico_03-2024,5,satisfacao_servico,3
89,10,32,M,satisfacao_servico_03-2024,4,satisfacao_servico,3